### ISSUE TITLE
import datapot as dp cannot import name 'mean_autocorrelation'

### ISSUE THREAD

**Issue by Motorrat** [bashalex/datapot#24]
Traceback (most recent call last):
  File "load-dataset-Adult-datapot.py", line 11, in <module>
    import datapot as dp
  File "../lib/python3.5/site-packages/datapot/__init__.py", line 11, in <module>
    from . import transformer
  File "../lib/python3.5/site-packages/datapot/transformer/__init__.py", line 5, in <module>
    from .timeseries_transformer import TimeSeriesTransformer
  File "../lib/python3.5/site-packages/datapot/transformer/timeseries_transformer.py", line 1, in <module>
    from tsfresh.feature_extraction.feature_calculators import (
ImportError: cannot import name 'mean_autocorrelation'

**Comment by Motorrat** [comment]
mean_autocorrelation was removed from tsfresh 
https://github.com/blue-yonder/tsfresh/blob/235091947cf7e8b05e35ccaf9bae41ebf58c47ce/CHANGES.rst#version-090
